### ISSUE TITLE
Problème couleur de fond des infos dynamiques sur tableau d'arrivées

### ISSUE THREAD

**Issue by JustYanns** [FloYoutube54/InfoGares#55]
Bonsoir,

J'ai constaté que la couleur de fond des informations dynamiques était erronée sur le tableau des arrivées.
En effet, celle-ci est bleue, au lieu d'être verte. (voir l'image jointe)

![image](https://user-images.githubusercontent.com/41501734/185216667-255189b2-8858-42bf-b0d3-34d1e3b899d6.png)

Ayant constaté que les pull request ont toutes été créées par les développeurs du projet, j'ai préféré éviter d'en créer une, cependant je propose le correctif suivant :
```css
.rows.rows-arrivals .row-group:nth-of-type(odd) .train-information-dynamic {
    background-color: #217a42;
}

.rows.rows-arrivals .row-group:nth-of-type(even) .train-information-dynamic {
    background-color: #0c5639;
}
```
Merci d'avance
